[[redirects]]
force = true
from = '/api/*'
status = 200
to = 'https://api.b365api.com/:splat'

[[redirects]]
from = '/*'
status = 200
to = '/index.html'

[build]
command = 'npm run build'
environment = {NODE_VERSION = '14'}

[dev]
autoLaunch = false