export const SHORT_CODE_CANCELED=5
export const SHORT_CODE_PLAYING=1
export const SHORT_CODE_REMOVED=99
export const HALFTIME_STRING="HT"
export const API_STATS_URL = "https://api.balldontlie.io/v1/";
export const GAMES_ENDPOINT = "games";
export const MATCHES_LOG_STRING = "Matches by date";
export const TEAM_MATCHES_LOG_STRING = "Matches by team";
export const STATS_ENDPOINT = "teams";
export const MATCH_STATS_LOG_API = "Match stats";
export const STANDINGS_LOG_STRING = "Standings";
export const TEAM_ID_PEÑAROL = 293;
export const LEAGUE_ID_URY = 110;